# Generated by Django 5.1.3 on 2024-11-17 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('photos', models.ImageField(blank=True, null=True, upload_to='events/photos/')),
                ('old_photos', models.ImageField(blank=True, null=True, upload_to='events/old_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('place', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='events.event')),
            ],
        ),
    ]
