# Generated by Django 5.1.3 on 2024-12-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_delete_requested_event_requested_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('cultural', 'Cultural'), ('Music', 'Music'), ('Sports', 'Sports'), ('Art', 'Art'), ('Tech', 'Tech'), ('Food', 'Food')], default='cultural', max_length=20),
        ),
    ]
