# Generated by Django 5.1.3 on 2024-12-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='visits',
            field=models.IntegerField(default=0),
        ),
    ]
