# Generated by Django 5.1.3 on 2024-12-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_visits'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='phone',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
