# Generated by Django 5.1.3 on 2025-01-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
