# Generated by Django 5.1.3 on 2025-01-14 17:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventuser',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='eventuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
