# Generated by Django 5.1.3 on 2025-02-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
