# Generated by Django 5.1.3 on 2025-02-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='category',
            field=models.ManyToManyField(related_name='competitions', to='events.category'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ManyToManyField(related_name='events', to='events.category'),
        ),
    ]
