# Generated by Django 5.1.3 on 2025-02-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_competition_category_remove_event_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('cultural', 'Cultural'), ('music', 'Music'), ('sports', 'Sports'), ('art', 'Art'), ('tech', 'Tech'), ('food', 'Food')], max_length=20, unique=True),
        ),
    ]
