# Generated by Django 5.1.3 on 2025-03-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
